#!/bin/bash

# 'Hostname' of the host which will collect data
HOSTNAME=$3
#
SVC_USER=$1
#
SVC_PWD=$2
#
D_TYPE=$5

D_HOSTNAME=$4

/usr/bin/python /usr/local/zabbix/huawei/hwv3_discovery.py  --clusters "$HOSTNAME" --user "$SVC_USER" --password "$SVC_PWD" --hostname "$D_HOSTNAME"  --discovery-types "$D_TYPE"
