#!/bin/bash
# 'Hostname' of the host which will collect data


nohup /usr/local/python /usr/local/zabbix/huawei/hwv3_wbem.py  --cluster "$1" --user "$2" --password "$3" --hostname "$4"  --proxy "$5"  --serial "$6"  --fun "$7"  >  /dev/null 2>&1 &
