#!/bin/bash
# 'Hostname' of the host which will collect data

echo $(date +'%Y-%m-%d %H:%M:%S')
timeout 60m   nohup /usr/bin/python3 /usr/local/zabbix/huawei/hwv3_wbem.py  --cluster "$1" --user "$2" --password "$3" --hostname "$4"  --proxy "$5"   --fun "$6"  >  /dev/null 2>&1 &
