#!/bin/bash

# 'Hostname' of the host which will collect data
HOSTNAME=$3
#
SVC_USER=$1
#
SVC_PWD=$2
#
D_TYPE=$6

D_HOSTNAME=$4

SMIS_PORT=$5


#日立存储自动发现

/usr/bin/python /usr/local/zabbix/hdsgx00/hds_vsp_gx00_discovery.py  --clusters "$HOSTNAME" --user "$SVC_USER" --password "$SVC_PWD" --hostname "$D_HOSTNAME" --smis_port "$SMIS_PORT" --discovery-types "$D_TYPE"  



