#!/bin/bash

fd="/usr/local/zabbix_proxy/share/zabbix/externalscripts/dev.ping.result"

#判断文件是否存在
[ -f $fd ]&&{
	echo "脚本已存在"
	exit 1

}

#新建文件
#文件写入内容
echo "新建文件并写入内容"
cat>$fd<<EOF
#!/bin/bash

HOST=\$1
res=\$(ping -c 2 -W 1 -i 0.5 "\$HOST")
echo "\$res"
EOF

#文件赋权和更新所有人
echo "文件赋权和更新所有人"
chmod o+x $fd && chown zabbix:zabbix $fd


#!/bin/bash

HOST=$1
res=$(ping -c 2 -W 1 -i 0.5 "$HOST")
echo "$res"
